# Generated by Django 5.0.6 on 2024-08-03 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_rename_countinstock_product_countinstock'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='totolPrice',
            new_name='totalPrice',
        ),
    ]
