# Generated by Django 5.0.6 on 2024-08-11 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_rename_totolprice_order_totalprice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='devliveredAt',
            new_name='deliveredAt',
        ),
    ]
